spring:
  application:
    name: catalog-service
  data:
    rest:
      base-path: /catalog-service
    mongodb:
      host: ${MICROXS_COMMERCE_MONGO_SERVICE_HOST:localhost}
      port: ${MICROXS_COMMERCE_MONGO_SERVICE_PORT:27017}
      database: catalog
      repositories:
        enabled: true


# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port