spring:
  application:
    name: catalog-service

---
spring:
  profiles: default
  data:
    rest:
      base-path: /catalog-service
    mongodb:
      host: localhost
      port: 27017
      database: catalog
      repositories:
        enabled: true
---
spring:
  profiles: development
  cloud:
    config:
      uri: http://${MICROXS_COMMERCE_CONFIG_SERVICE_HOST:localhost}:${MICROXS_COMMERCE_CONFIG_SERVICE_PORT:8888}
---
spring:
  profiles: cloud
  cloud:
    config:
      uri: http://${MICROXS_COMMERCE_CONFIG_SERVICE_HOST:localhost}:${MICROXS_COMMERCE_CONFIG_SERVICE_PORT:8888}
